# https://taskfile.dev/usage/
version: "3"
tasks:
  default: bun run dev
  dev: bun run dev
  s: bun run vite --port 4440
  build: bun run build
  pre: |
    bun run build
    bun preview

  ## Setup
  add-vite: bun add -d vite
  update: bun update
